# .readthedocs.yml

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    
python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
    - method: pip
      path: ./thermosteam
    
submodules:
  include:
    - thermosteam
    
sphinx:
   configuration: docs/conf.py
   