# .readthedocs.yml

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    
sphinx:
   configuration: docs/conf.py
   